// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	NPC_1 = 0,
	NPC_2 = 1,
	NPC_3 = 2,
	North_Delta_Adapt_Intro = 3,
	Start_Future_Vision = 4,
	Direct_To_Beach = 5,
}
